apiVersion: v1
kind: Service
metadata:
  name: cfc-frontend
  labels:
    app: cfc-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000  
  selector:
    app: cfc-frontend